<?php
/**
 * Roman Yurkhanov
 *
 * Email :: ferrumdp@gmail.com
 * Linkedin :: https://www.linkedin.com/in/roman-yurkhanov-322035122/
 *
 * Copyright 2023-present Roman Yurkhanov. All rights reserved.
 * See license.txt for license details.
 */

/**
 * @var \RomanYurkhanov\Modal\Block\Modal $block
 * @var \Magento\Framework\Escaper $escaper
 */

$modalTimeout = $block->getModalTimeout();
$modalLogoSrc = $block->getModalLogoSrc();
$modalTitle = $block->getModalTitle();
$modalMessage = $block->getModalMessage();
$modalCtaTitle = $block->getModalCtaTitle();
$modalCtaUrl = $block->getModalCtaUrl();
?>

<div
    id="modal-block"
    class="modal"
    data-timeout="<?= $escaper->escapeHtmlAttr($modalTimeout) ?>"
    data-cta-title="<?= $escaper->escapeHtmlAttr($modalCtaTitle) ?>"
    data-cta-url="<?= $escaper->escapeHtmlAttr($modalCtaUrl) ?>"
>
    <?php if ($modalLogoSrc): ?>
        <img class="modal-logo" src="<?= $escaper->escapeHtml($modalLogoSrc) ?>" alt="<?= $escaper->escapeHtml($modalTitle) ?>" />
    <?php endif; ?>

    <h2 class="modal-title" data-bind="html: '<?= $escaper->escapeHtmlAttr($modalTitle) ?>'"></h2>

    <span data-bind="html: '<?= $escaper->escapeHtmlAttr($modalMessage) ?>'"></span>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "RomanYurkhanov_Modal/js/modal": {}
        }
    }
</script>
